import Head from "next/head";
import Image from "next/image";
import Wellcome from "../components/elements/Wellcome";
import Guide from "../components/elements/Guide";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Wellcome />
        <div className={styles.grid}>
          <Guide
            title="Documentation"
            href="https://nextjs.org/docs"
            description="Find in-depth information about Next.js features and API."
          />

          <Guide
            title="Learn"
            href="https://nextjs.org/learn"
            description="Learn about Next.js in an interactive course with quizzes!"
          />

          <Guide
            title="Examples"
            href="https://github.com/vercel/next.js/tree/master/examples"
            description="Discover and deploy boilerplate example Next.js projects."
          />

          <Guide
            title="Deploy"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            description="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
